version: "2"
services:
    php:
        build: .
        expose:
            - 9000
        volumes:
            - ./app:/var/www/html
            - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    nginx:
        image: nginx:1.12-alpine
        links:
            - php
        volumes:
            - ./app:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - 8700:80
