version: "2"
services:
    php:
        image: sanwas/php7:alpine
        volumes:
            - ./app:/var/www/html
            - ./alpine/php.ini:/etc/php7/conf.d/alpine.ini
    nginx:
        image: nginx:1.12-alpine
        links:
            - php
        volumes:
            - ./app:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - 8700:80
