version: "2"
services:
    mysql:
        mem_limit: 128m
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=TfR6KN1kbnSnseq3
            - MYSQL_DATABASE=processwire
        command:
            - mysqld
            - --max_allowed_packet=64M
            - --innodb_buffer_pool_size=8M
            - --max_connections=16
            - --innodb_log_buffer_size=256K
            - --query_cache_size=0
            - --performance_schema=0
            - --key_buffer_size=1K
            - --thread_stack=300K
    apache:
        build: .
        volumes:
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
            - ./processwire:/var/www
        ports:
            - 7480:80