version: "2"
services:
  postgres-slave:
    build: .
    links:
      - postgres-master
    ports:
      - 5501:5432
    environment:
      REPLICATION_ROLE: slave
      POSTGRES_MASTER_SERVICE_HOST: postgres-master


  postgres-master:
    build: .
    environment:
      REPLICATION_ROLE: master
    ports:
      - 5500:5432
