version: "2.2"
services:
  postgres-master:
    # get into: psql -h 127.0.0.1 -p 5500 -U app
    # note: some Postgres client might not support SSL connection,
    # which require to connect to this server
    build: .
    environment:
      REPLICATION_ROLE: master
      POSTGRES_USER: app
      # use docker-compose.override.yml to store your password
      POSTGRES_PASSWORD: TODOyourPassWord
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./conf.d:/var/lib/postgresql/postgresql.conf.d:ro
      # enable initial dumps here
      # - ./dump:/docker-entrypoint-initdb.d/
    ports:
      - 5500:5432
    restart: on-failure
    mem_limit: 280m
    memswap_limit: 0
  postgres-slave:
    build: .
    links:
      - postgres-master
    ports:
      - 5501:5432
    restart: on-failure
    memswap_limit: 0
    mem_limit: 280m
    volumes:
      - ./backup:/var/backups/postgresql
      - ./conf.d:/var/lib/postgresql/postgresql.conf.d:ro
    environment:
      REPLICATION_ROLE: slave
      POSTGRES_MASTER_SERVICE_HOST: postgres-master
  postgres-pool:
    build: ./pool
    volumes:
      - ./pool/pgpool.conf:/etc/pgpool2/pgpool.conf
      - ./pool/pool_hba.conf:/etc/pgpool2/pgpool.conf
    ports:
      - 9999:9999
    links:
      - postgres-master
      - postgres-slave
  # to backup, run following
  # docker-compose exec postgres-slave pg_back -U app
